main_home:

  path: /
  controller: App\Controller\HomeController::index

  # routes.yaml

# routes.yaml

recherche:
  path: /recette/recherche
  controller: App\Controller\RecetteController::rechercheRecette

detail_recette:
  path: /recette/detail/{id}
  controller: App\Controller\RecetteController::detailRecette


health_plan:
  path: /health
  controller: App\Controller\RecetteController::genererPlanAlimentaire


main_about:
  path: /about
  controller: App\Controller\MainController::about

movie_list:
  path: /movies
  controller: App\Controller\MovieController::list

movie_show:
  path: /movie
  controller: App\Controller\MovieController::show

login:
  path: /login
  controller: App\Controller\AuthController::login

logout:
  path: /logout
  controller: App\Controller\AuthController::logout

register:
  path: /register
  controller: App\Controller\AuthController::register

confirm:
  path: /confirm/{token}
  controller: App\Controller\AuthController::confirm

forgot_password:
  path: /forgot-password
  controller: App\Controller\AuthController::forgotPassword

favorite-list:
  path: /favorite
  controller: App\Controller\FavoriteController::showFavorites

toggle-favorite:
  path: /recipe/toggle-favorite
  controller: App\Controller\FavoriteController::toggleFavorite

recipe_rate:
  path: /recipe/rate
  controller: App\Controller\RatingController::submitRating
  methods: [POST]

recipe_delete_rating:
  path: /recipe/rating/delete
  controller: App\Controller\RatingController::deleteRating
  methods: [POST]

recipe_ratings:
  path: /recipe/{id}/ratings
  controller: App\Controller\RatingController::getRatings
  methods: [GET]